version: "3.8"

services:
  backend:
    build: .
    container_name: new_backend_app
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - "5001:5000"   # VPS port 5001 â†’ container port 5000

  mongo:
    image: mongo:6
    container_name: new_mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  mongo-express:
    image: mongo-express:latest
    container_name: new_mongo_ui
    restart: always
    ports:
      - "8082:8081"   # changed to avoid conflict
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongo_data:
